baseURL = "https://me.bitfiend.com/"
languageCode = "en-us"
theme = "MM-Blog"
title = "BitFiend Coder"
[params]
NotFoundText = "Uh oh... looks like the page your looking for isn't here."
description = "I am a full-stack software developer with a focus on web technologies. I love building digital solutions for people in order to make their lives better. I'm always trying out new projects and technologies to further better my craft. My personal coding philosophy is: simpler is always better, try to be language/framework agnostic, and never assume anything."
email = "your@email.com"
headline = "Big bearded Full-Stack Developer with an obsession for red plaid and clean code."
name = "Amos Garner"
[params.footer]
location = "TN"
[[params.index.columns]]
description = "meandering monologues, objective opinions, and humorous heresy."
link = "/blog"
link_text = "Learn More"
title = "Blog"
[[params.index.columns]]
description = "Information about my background, education, and experience."
link = "/resume"
link_text = "Learn More"
title = "Resumé"
[params.navigation]
link = "/"
[[params.navigation.right.links]]
title = "Presentations"
link = "/presentations"
[[params.navigation.right.links]]
title = "Presentations"
link = "/presentations"
[[params.navigation.right.links]]
title = "Resumé"
link = "/resume"
[[params.navigation.right.links]]
title = "Contact"
link = "/contact"
[params.navigation.social]
icon = "link"
prefix = "fas"
title = "Social Media"
[[params.navigation.social.links]]
icon = "linkedin"
link = "https://www.linkedin.com/in/amos-garner-34630694/"
prefix = "fab"
title = "LinkedIn"
[[params.navigation.social.links]]
icon = "twitter-square"
link = "https://twitter.com/BitFiendCoder"
prefix = "fab"
title = "Twitter"
[[params.navigation.social.links]]
icon = "github-square"
link = "https://github.com/AmosGarner"
prefix = "fab"
title = "Github"
