baseURL = "http://me.bitfiend.com/"
languageCode = "en-us"
title = "Me.Bitfiend"
theme = "bitfiend-resume"

[params]
    name = "Amos Garner"
    description = "Big bearded Full-Stack Developer with an obsession for red plaid and clean code."
    email = "your@email.com"

    [params.navigation]
        brand = "Bitfiend Coder"
        link = "/"
            [params.navigation.right]
                [[params.navigation.right.links]]
                    title = "Blog"
                    prefix = "fab"
                    icon = "readme"
                    link = "/blog"
                [[params.navigation.right.links]]
                    title = "Resumé"
                    prefix = "fas"
                    icon = "address-card"
                    link = "/resume"
                [[params.navigation.right.links]]
                    title = "Contact"
                    prefix = "far"
                    icon = "envelope"
                    link = "/contact"

    [params.header]
        main = "Amos Garner"
        sub = "Coder - Gamer - Creator"

    [params.footer]
        [params.footer.location]
            title = "Location"
            address = ["Knoxville, TN", "United States of America"]
        [params.footer.social]
            title = "My Digital Footprint"
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/AmosGarner"
