[build]
  publish = "public"
  command = "git submodule update --init --recursive; hugo"

[context.production]
  command = "git submodule update --init --recursive; hugo"
  [context.production.environment]
    HUGO_VERSION = "0.39"
    HUGO_ENV = "production"
