[build]
  publish = "public"
  command = "hugo; git submodule update --init --recursive"

[context.production]
  command = "hugo"
  [context.production.environment]
    HUGO_VERSION = "0.39"
    HUGO_ENV = "production"
